# site settings
destination: _site_dev/
title: HiveVM
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hivevm.com" # the base hostname & protocol for your site

# build settings
markdown: kramdown
highlighter: rouge

include: ['_pages']

encoding: utf-8
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', '*.bat', '.jekyll-metadata']

# error pages
collections:
  error_pages:
    output: true
    permalink: /:path.html

# assets
assets:
  prefix: "/assets"
  sources:
    - _assets/fonts
    - _assets/css
    - _assets/js
    - _assets/images

# blog
permalink: /blog/:year/:title/

jekyll-archives:
  enabled:
    - year
    - categories
  layouts:
    year: archive_time
    category: archive_name
  permalinks:
    year: '/blog/:year/'
    category: '/blog/:name/'
# comments
disqus:
  shortname: hivevm

# navigation
navigation:
  - title: Home
    href: /
  - title: Virtual Servers
    href: /hosting/vps/
  - title: Shared Hosting
    href: /hosting/shared/
  - title: About
    dropdown:
    - title: About Us
      href: /about/
    - title: Locations
      href: /locations/
    - title: Blog
      href: /blog/
  - title: Clients
    dropdown:
      - title: Client Area
        href: http://clients.hivevm.com/
      - title: VPS Panel
        href: http://vps.hivevm.com/
      - title: Shared Panel
        href: http://cpanel.hivevm.com/
